apiVersion: v2
name: nira-payment-gateway
description: A Helm chart for MOSIP Registration Processor Payments
type: application
version: 12.0.1
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - nira-payment-gateway
  - regproc
maintainers:
  - email: info@mosip.io
    name: MOSIP
