apiVersion: v2
name: regproc-group8
description: A Helm chart for NIRA Citizenship Verification Registration Processor Group 8 stage
type: application
version: 12.0.1
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - regproc-group8
  - regproc
maintainers:
  - email: info@mosip.io
    name: MOSIP
